<a href="https://colab.research.google.com/github/25053459-Lincoln/data-science-toolkit/blob/main/Tweek31007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

# Create a 2x2 NumPy array
array_2x2 = np.array([[1, 2], [3, 4]])

print("1. Create a 2x2 NumPy array:")
print(array_2x2)
print("-" * 20)

1. Create a 2x2 NumPy array:
[[1 2]
 [3 4]]
--------------------


In [9]:
# Create a 3x NumPy array
# np.random.rand(rows, cols)
random_array_3x4 = np.random.rand(3, 4)

print("2. Create a 3x4 NumPy array:")
print(random_array_3x4)
print("-" * 20)

2. Create a 3x4 NumPy array:
[[0.72559937 0.90605506 0.87976664 0.50721765]
 [0.84939298 0.29444207 0.22306439 0.30185152]
 [0.65731253 0.15958045 0.30071745 0.83711958]]
--------------------


In [6]:
# Create a NumPy array of all 1s(example 3x3)
ones_array = np.ones((3, 3))

# Create a NumPy array of all zeros (example 2x5)
zeros_array = np.zeros((2, 5))

print("3. Create a NumPy array of all 1s:")
print(ones_array)
print("\n3. Create a NumPy array of all zeros:")
print(zeros_array)
print("-" * 20)

3. Create a NumPy array of all 1s:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

3. Create a NumPy array of all zeros:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
--------------------


In [5]:
# Create a random 6x3 NumPy array
random_array_6x3 = np.random.randint(0, 10, size=(6, 3)) # 创建 0 到 9 的整数

# Transposed Array
transposed_array = random_array_6x3.T

print("4. Raw 6x3 random NumPy array (shape:", random_array_6x3.shape, "):")
print(random_array_6x3)
print("\n4. Transposed Array (shape:", transposed_array.shape, "):")
print(transposed_array)
print("-" * 20)

4. Raw 6x3 random NumPy array (shape: (6, 3) ):
[[0 1 5]
 [5 1 2]
 [7 1 5]
 [9 7 7]
 [4 1 8]
 [5 6 4]]

4. Transposed Array (shape: (3, 6) ):
[[0 5 7 9 4 5]
 [1 1 1 7 1 6]
 [5 2 5 7 8 4]]
--------------------


In [4]:
# Set the dimension
n, p, m = 4, 3, 2

# Create the first array (nxp)
A = np.random.rand(n, p)

# Create the second array (pxm)
B = np.random.rand(p, m)

# Dot product (matrix multiplication)
# use np.dot(A, B) 或 A @ B
dot_product = A @ B

print(f"5. array A (n={n}, p={p}) The shape of: {A.shape}")
print(f"5. array B (p={p}, m={m}) The shape of: {B.shape}")
print("5. array A Dot product (matrix multiplication)  B:")
print(dot_product)
print("5. The shape of the dot product result:", dot_product.shape)
print("-" * 20)

5. array A (n=4, p=3) The shape of: (4, 3)
5. array B (p=3, m=2) The shape of: (3, 2)
5. array A Dot product (matrix multiplication)  B:
[[0.56174862 0.86178204]
 [0.35277583 0.87366337]
 [0.55210885 1.29310046]
 [0.51662864 1.00768467]]
5. The shape of the dot product result: (4, 2)
--------------------
