<a href="https://colab.research.google.com/github/25053459-Lincoln/data-science-toolkit/blob/main/Tweek31007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 创建一个 2x2 的 NumPy 数组
array_2x2 = np.array([[1, 2], [3, 4]])

print("1. 创建一个 2x2 的 NumPy 数组:")
print(array_2x2)
print("-" * 20)

1. 创建一个 2x2 的 NumPy 数组:
[[1 2]
 [3 4]]
--------------------


In [2]:
# 创建一个 3x4 的随机 NumPy 数组
# np.random.rand(rows, cols)
random_array_3x4 = np.random.rand(3, 4)

print("2. 创建一个 3x4 的随机 NumPy 数组:")
print(random_array_3x4)
print("-" * 20)

2. 创建一个 3x4 的随机 NumPy 数组:
[[0.18573921 0.68596803 0.99369884 0.69590944]
 [0.60611905 0.17757632 0.37941571 0.25077595]
 [0.09883627 0.71086352 0.1996082  0.67363888]]
--------------------


In [ ]:
# 创建一个全 1 的 NumPy 数组 (例如 3x3)
ones_array = np.ones((3, 3))

# 创建一个全 0 的 NumPy 数组 (例如 2x5)
zeros_array = np.zeros((2, 5))

print("3. 创建一个全 1 的 NumPy 数组:")
print(ones_array)
print("\n3. 创建一个全 0 的 NumPy 数组:")
print(zeros_array)
print("-" * 20)

In [ ]:
# 创建一个 6x3 的随机 NumPy 数组
random_array_6x3 = np.random.randint(0, 10, size=(6, 3)) # 创建 0 到 9 的整数

# 转置数组
transposed_array = random_array_6x3.T

print("4. 原始 6x3 随机 NumPy 数组 (形状:", random_array_6x3.shape, "):")
print(random_array_6x3)
print("\n4. 转置后的数组 (形状:", transposed_array.shape, "):")
print(transposed_array)
print("-" * 20)

In [ ]:
# 设定维度
n, p, m = 4, 3, 2

# 创建第一个数组 (nxp)
A = np.random.rand(n, p)

# 创建第二个数组 (pxm)
B = np.random.rand(p, m)

# 计算点积 (矩阵乘法)
# 可以使用 np.dot(A, B) 或 A @ B
dot_product = A @ B

print(f"5. 数组 A (n={n}, p={p}) 的形状: {A.shape}")
print(f"5. 数组 B (p={p}, m={m}) 的形状: {B.shape}")
print("5. 数组 A 的点积 (矩阵乘法) B:")
print(dot_product)
print("5. 点积结果的形状:", dot_product.shape)
print("-" * 20)